import React, { useState, useEffect } from "react";
import {
  Upload,
  Link,
  FileText,
  DollarSign,
  Tag,
  Package,
  Image,
  Plus,
  X,
  IndianRupee,
  VideoIcon,
  Share2,
  Copy,
  Check,
} from "lucide-react";
import { API_BASE_URL } from "../../../config";

// Share Popup Component
const SharePopup = ({ isOpen, onClose, businessShareLink, businessTitle }) => {
  const [copied, setCopied] = useState(false);

  // Only use the shareLink from backend database
  const shareUrl = businessShareLink;

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(shareUrl);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy: ", err);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-2xl shadow-2xl max-w-md w-full p-6">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-xl font-bold text-gray-800">Share Business</h3>
          <button
            onClick={onClose}
            className="p-2 hover:bg-gray-100 rounded-full transition-colors"
          >
            <X className="w-5 h-5 text-gray-500" />
          </button>
        </div>

        <div className="space-y-4">
          <p className="text-gray-600">Share this business with others:</p>

          {shareUrl ? (
            <>
              <div className="flex items-center gap-2 p-3 bg-gray-50 rounded-lg border">
                <input
                  type="text"
                  value={shareUrl}
                  readOnly
                  className="flex-1 bg-transparent text-sm text-gray-700 outline-none"
                />
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-2 px-3 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors text-sm font-medium"
                >
                  {copied ? (
                    <>
                      <Check className="w-4 h-4" />
                      Copied!
                    </>
                  ) : (
                    <>
                      <Copy className="w-4 h-4" />
                      Copy
                    </>
                  )}
                </button>
              </div>

              <div className="text-xs text-gray-500">
                Anyone with this link can view your business details
              </div>
            </>
          ) : (
            <div className="text-center py-6">
              <div className="inline-flex items-center justify-center w-16 h-16 bg-yellow-100 rounded-full mb-4">
                <X className="w-8 h-8 text-yellow-600" />
              </div>
              <h3 className="text-lg font-medium text-gray-900 mb-2">
                Share Link Not Available
              </h3>
              <p className="text-gray-500 mb-4">
                This business doesn't have a share link generated yet. Please
                contact support.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

// Business Form Component
const BusinessForm = ({ isOpen, onClose, onCreated }) => {
  const [formData, setFormData] = useState({
    title: "",
    category: "",
    type: "product",
    image: { url: "", key: "" },
    documents: { url: "", key: "" },
    videoLink: "",
    link: "",
    description: "",
    mrp: "",
    offerPrice: "",
  });

  const [previewImage, setPreviewImage] = useState(null);
  const [loading, setLoading] = useState(false);
  const [fileUploading, setFileUploading] = useState(false);
  const [error, setError] = useState("");

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const handleFileChange = async (e, fieldName) => {
    const file = e.target.files[0];
    if (!file) return;

    setFileUploading(true);
    setError("");

    try {
      // Get pre-signed upload URL for MyBusiness
      const token = sessionStorage.getItem("clienttoken");
      const res = await fetch(
        `${API_BASE_URL}/client/upload-url-mybusiness?fileName=${file.name}&fileType=${file.type}`,
        {
          headers: { Authorization: `Bearer ${token}` },
        }
      );

      if (!res.ok) throw new Error("Failed to get upload URL");
      const data = await res.json();

      if (!data.success)
        throw new Error(data.message || "Failed to get upload URL");

      // Upload file to S3
      const uploadRes = await fetch(data.url, {
        method: "PUT",
        body: file,
        headers: { "Content-Type": file.type },
      });

      if (!uploadRes.ok) throw new Error("Failed to upload file to S3");

      // Store only the S3 key, URL will be generated by backend
      if (fieldName === "image") {
        // Show a temporary preview using the presigned URL
        setPreviewImage(data.url);
        setFormData((prev) => ({
          ...prev,
          image: { url: "", key: data.key }, // Only store key, URL will be set by backend
        }));
      } else if (fieldName === "documents") {
        setFormData((prev) => ({
          ...prev,
          documents: { url: "", key: data.key }, // Only store key, URL will be set by backend
        }));
      }
    } catch (err) {
      setError(`File upload failed: ${err.message}`);
      console.error("File upload error:", err);
    } finally {
      setFileUploading(false);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError("");
    try {
      const token = sessionStorage.getItem("clienttoken");
      const payload = {
        ...formData,
        mrp: formData.mrp ? Number(formData.mrp) : 0,
        offerPrice: formData.offerPrice ? Number(formData.offerPrice) : null,
      };
      // Only send required fields for backend
      const requiredFields = [
        "title",
        "category",
        "type",
        "videoLink",
        "description",
        "image",
        "mrp",
      ];
      for (let field of requiredFields) {
        if (!payload[field] || (field === "image" && !payload.image.key)) {
          setError("All required fields must be filled.");
          setLoading(false);
          return;
        }
      }
      // Remove empty documents if not uploaded
      if (!payload.documents || !payload.documents.key) {
        delete payload.documents;
      }
      const res = await fetch(`${API_BASE_URL}/client/business`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify(payload),
      });
      const data = await res.json();
      if (data.success) {
        onCreated();
        handleReset();
        onClose();
      } else {
        setError(data.message || "Failed to create business.");
      }
    } catch (err) {
      setError("Error creating business.");
    } finally {
      setLoading(false);
    }
  };

  const handleReset = () => {
    setFormData({
      title: "",
      category: "",
      type: "product",
      image: { url: "", key: "" },
      documents: { url: "", key: "" },
      videoLink: "",
      link: "",
      description: "",
      mrp: "",
      offerPrice: "",
    });
    setPreviewImage(null);
    setError("");
    setFileUploading(false);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-2xl shadow-2xl max-w-4xl w-full max-h-[90vh] overflow-y-auto">
        {/* Modal Header */}
        <div className="sticky top-0 bg-white border-b border-gray-200 px-8 py-6 flex items-center justify-between rounded-t-2xl">
          <div>
            <h2 className="text-2xl font-bold text-gray-800">
              Add Business Information
            </h2>
            <p className="text-gray-600 mt-1">
              Fill in the details for your product or service
            </p>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-gray-100 rounded-full transition-colors"
          >
            <X className="w-6 h-6 text-gray-500" />
          </button>
        </div>
        {/* Modal Content */}
        <form className="p-8" onSubmit={handleSubmit}>
          <div className="space-y-6">
            {/* Title */}
            <div className="space-y-2">
              <label className="flex items-center text-sm font-medium text-gray-700">
                <Package className="w-4 h-4 mr-2 text-blue-500" /> Title *
              </label>
              <input
                type="text"
                name="title"
                value={formData.title}
                onChange={handleInputChange}
                className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-colors"
                placeholder="Enter the title"
                required
              />
            </div>
            {/* Category and Type Row */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-2">
                <label className="flex items-center text-sm font-medium text-gray-700">
                  <Tag className="w-4 h-4 mr-2 text-green-500" /> Category *
                </label>
                <input
                  type="text"
                  name="category"
                  value={formData.category}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-colors"
                  placeholder="e.g., Electronics, Consulting, etc."
                  required
                />
              </div>
              <div className="space-y-2">
                <label className="flex items-center text-sm font-medium text-gray-700">
                  <Package className="w-4 h-4 mr-2 text-purple-500" /> Type *
                </label>
                <select
                  name="type"
                  value={formData.type}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-colors"
                  required
                >
                  <option value="product">Product</option>
                  <option value="service">Service</option>
                </select>
              </div>
            </div>
            {/* Image Upload */}
            <div className="space-y-2">
              <label className="flex items-center text-sm font-medium text-gray-700">
                <Image className="w-4 h-4 mr-2 text-pink-500" /> Produce/Service
                Image *
              </label>
              <div className="flex items-center space-x-4">
                <div className="flex-1">
                  <input
                    type="file"
                    onChange={(e) => handleFileChange(e, "image")}
                    accept="image/*"
                    disabled={fileUploading}
                    className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-colors file:mr-4 file:py-2 file:px-4 file:rounded-lg file:border-0 file:text-sm file:font-medium file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100 disabled:opacity-50 disabled:cursor-not-allowed"
                    required
                  />
                </div>
                {fileUploading && (
                  <div className="w-20 h-20 flex items-center justify-center bg-gray-100 rounded-lg">
                    <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-blue-600"></div>
                  </div>
                )}
                {previewImage && !fileUploading && previewImage !== "" && (
                  <div className="w-20 h-20">
                    <img
                      src={previewImage}
                      alt="Preview"
                      className="w-full h-full object-cover rounded-lg border-2 border-gray-200"
                    />
                  </div>
                )}
              </div>
            </div>
            {/* Video Link */}
            <div className="space-y-2">
              <label className="flex items-center text-sm font-medium text-gray-700">
                <VideoIcon className="w-4 h-4 mr-2 text-red-500" /> Video Link *
              </label>
              <input
                type="url"
                name="videoLink"
                value={formData.videoLink}
                onChange={handleInputChange}
                className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-colors"
                placeholder="https://...."
                required
              />
            </div>
            {/* Resource Link */}
            <div className="space-y-2">
              <label className="flex items-center text-sm font-medium text-gray-700">
                <Link className="w-4 h-4 mr-2 text-blue-500" /> Resource Link
              </label>
              <input
                type="url"
                name="link"
                value={formData.link}
                onChange={handleInputChange}
                className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-colors"
                placeholder="https://...."
              />
            </div>

            {/* Description */}
            <div className="space-y-2">
              <label className="text-sm font-medium text-gray-700">
                Description *
              </label>
              <textarea
                name="description"
                value={formData.description}
                onChange={handleInputChange}
                rows={4}
                className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-colors resize-vertical"
                placeholder="Describe your product or service..."
                required
              />
            </div>
            {/* Price and Offer Row */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-2">
                <label className="flex items-center text-sm font-medium text-gray-700">
                  <IndianRupee className="w-4 h-4 mr-2 text-green-600" /> MRP
                </label>
                <input
                  type="number"
                  name="mrp"
                  value={formData.mrp}
                  onChange={handleInputChange}
                  step="0.01"
                  min="0"
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-colors"
                  placeholder="0.00"
                  required
                />
              </div>
              <div className="space-y-2">
                <label className="flex items-center text-sm font-medium text-gray-700">
                  <IndianRupee className="w-4 h-4 mr-2 text-orange-600" /> Offer
                  Price
                </label>
                <input
                  type="number"
                  name="offerPrice"
                  value={formData.offerPrice}
                  onChange={handleInputChange}
                  step="0.01"
                  min="0"
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-colors"
                  placeholder="0.00"
                />
              </div>
            </div>
            {/* Error and Buttons */}
            {error && <div className="text-red-600 font-medium">{error}</div>}
            <div className="flex flex-col sm:flex-row gap-4 pt-6 border-t border-gray-200">
              <button
                type="submit"
                disabled={loading}
                className="flex-1 bg-gradient-to-r from-blue-600 to-purple-600 text-white py-3 px-6 rounded-lg hover:from-blue-700 hover:to-purple-700 transition-all duration-200 font-medium shadow-lg hover:shadow-xl transform hover:-translate-y-0.5"
              >
                {loading ? "Submitting..." : "Submit Form"}
              </button>
              <button
                type="button"
                onClick={handleReset}
                className="sm:flex-none bg-gray-500 text-white py-3 px-6 rounded-lg hover:bg-gray-600 transition-colors font-medium"
              >
                Reset Form
              </button>
              <button
                type="button"
                onClick={onClose}
                className="sm:flex-none bg-gray-300 text-gray-700 py-3 px-6 rounded-lg hover:bg-gray-400 transition-colors font-medium"
              >
                Cancel
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
};

// Main Business Page Component
export default function BusinessPage() {
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [businesses, setBusinesses] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [sharePopup, setSharePopup] = useState({
    isOpen: false,
    businessShareLink: null,
    businessTitle: "",
  });

  const fetchBusinesses = async () => {
    setLoading(true);
    setError("");
    try {
      const token = sessionStorage.getItem("clienttoken");
      const res = await fetch(`${API_BASE_URL}/client/business`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      const data = await res.json();
      if (data.success && Array.isArray(data.data)) {
        setBusinesses(data.data);
      } else {
        setBusinesses([]);
        setError(data.message || "Failed to fetch businesses.");
      }
    } catch (err) {
      setError("Error fetching businesses.");
      setBusinesses([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchBusinesses();
  }, []);

  const openForm = () => setIsFormOpen(true);
  const closeForm = () => setIsFormOpen(false);
  const handleCreated = () => fetchBusinesses();

  const openSharePopup = (businessShareLink, businessTitle) => {
    // Only open popup if share link exists
    if (businessShareLink) {
      setSharePopup({ isOpen: true, businessShareLink, businessTitle });
    }
  };

  const closeSharePopup = () => {
    setSharePopup({
      isOpen: false,
      businessShareLink: null,
      businessTitle: "",
    });
  };

  return (
    <div className="h-screen flex flex-col bg-gradient-to-br from-gray-50 to-gray-100">
      {/* Fixed Header Section */}
      <div className="flex-shrink-0 bg-white shadow-sm border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <div>
                <h1 className="text-3xl font-bold text-gray-900">
                  My Business
                </h1>
                <p className="text-gray-600 mt-1">
                  Business Management Dashboard
                </p>
              </div>
            </div>
            <div className="text-right">
              <div className="text-sm text-gray-500 mb-1">Total Items</div>
              <div className="inline-flex items-center px-3 py-1 bg-blue-100 text-blue-800 text-sm font-medium rounded-full">
                <Package className="w-4 h-4 mr-2" />
                {businesses.length} Items
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Scrollable Content Area */}
      <div className="flex-1 overflow-y-auto">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          {/* Business Items Section */}
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6 mb-8">
            <div className="flex items-center justify-between mb-6">
              <div>
                <h2 className="text-xl font-semibold text-gray-900">
                  Business Items
                </h2>
                <p className="text-gray-600 mt-1">Your products and services</p>
              </div>
              <div className="flex items-center space-x-3">
                <button
                  onClick={fetchBusinesses}
                  disabled={loading}
                  className="inline-flex items-center px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-200 shadow-sm"
                >
                  <svg
                    className={`w-4 h-4 mr-2 ${loading ? "animate-spin" : ""}`}
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"
                    />
                  </svg>
                  {loading ? "Refreshing..." : "Refresh"}
                </button>
                <button
                  onClick={openForm}
                  className="inline-flex items-center px-6 py-2 bg-gradient-to-r from-blue-600 to-purple-600 text-white font-medium rounded-lg hover:from-blue-700 hover:to-purple-700 transition-all duration-200 shadow-md hover:shadow-lg transform hover:-translate-y-0.5"
                >
                  <Plus className="w-4 h-4 mr-2" /> Create New
                </button>
              </div>
            </div>

            {loading ? (
              <div className="text-center py-12">
                <div className="inline-flex items-center justify-center w-16 h-16 bg-blue-100 rounded-full">
                  <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
                </div>
                <p className="text-gray-500 mt-4 text-lg">
                  Loading businesses...
                </p>
              </div>
            ) : error ? (
              <div className="text-center py-12">
                <div className="inline-flex items-center justify-center w-20 h-20 bg-red-100 rounded-full mb-4">
                  <X className="w-10 h-10 text-red-600" />
                </div>
                <h3 className="text-lg font-medium text-gray-900 mb-2">
                  Error loading businesses
                </h3>
                <p className="text-red-500 mb-6">{error}</p>
                <button
                  onClick={fetchBusinesses}
                  className="inline-flex items-center px-4 py-2 bg-red-600 text-white text-sm font-medium rounded-lg hover:bg-red-700 transition-colors duration-200"
                >
                  Try Again
                </button>
              </div>
            ) : businesses.length === 0 ? (
              <div className="text-center py-16 bg-gray-50 rounded-xl border-2 border-dashed border-gray-300">
                <div className="inline-flex items-center justify-center w-20 h-20 bg-gray-100 rounded-full mb-4">
                  <Package className="w-10 h-10 text-gray-400" />
                </div>
                <h3 className="text-lg font-medium text-gray-900 mb-2">
                  No business items yet
                </h3>
                <p className="text-gray-500 mb-6">
                  Create your first product or service to get started.
                </p>
                <button
                  onClick={openForm}
                  className="inline-flex items-center px-4 py-2 bg-blue-600 text-white text-sm font-medium rounded-lg hover:bg-blue-700 transition-colors duration-200"
                >
                  <Plus className="w-4 h-4 mr-2" />
                  Create Your First Item
                </button>
              </div>
            ) : (
              <>
                {/* Business Items Grid */}
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                  {businesses.map((business) => (
                    <div
                      key={business._id}
                      className="group bg-white border border-gray-200 rounded-xl p-6 hover:shadow-lg hover:border-blue-300 transition-all duration-200"
                    >
                      <div className="flex items-start justify-between mb-4">
                        <div className="flex-1">
                          <div className="flex items-center gap-4 mb-4">
                            {business.image &&
                            business.image.url &&
                            business.image.url !== "" ? (
                              <img
                                src={business.image.url}
                                alt={business.title}
                                className="w-20 h-20 object-cover rounded-lg border-2 border-gray-200"
                              />
                            ) : (
                              <div className="w-20 h-20 bg-gray-100 rounded-lg border-2 border-gray-200 flex items-center justify-center">
                                <Image className="w-8 h-8 text-gray-400" />
                              </div>
                            )}
                            <div>
                              <h3 className="text-lg font-semibold text-gray-900 mb-1 group-hover:text-blue-600 transition-colors duration-200">
                                {business.title}
                              </h3>
                              <div className="text-sm text-gray-600 mb-1">
                                {business.category} | {business.type}
                              </div>
                              <div className="text-xs text-gray-400">
                                {new Date(
                                  business.createdAt
                                ).toLocaleDateString()}
                              </div>
                            </div>
                          </div>
                          <p className="text-gray-700 mb-3 line-clamp-3">
                            {business.description}
                          </p>
                          <div className="space-y-2 mb-4">
                            {business.videoLink && (
                              <a
                                href={business.videoLink}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="text-red-600 hover:text-red-700 underline text-sm block flex items-center"
                              >
                                <VideoIcon className="w-3 h-3 mr-1" />
                                Video Link
                              </a>
                            )}
                            {business.link && (
                              <a
                                href={business.link}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="text-blue-600 hover:text-blue-700 underline text-sm block flex items-center"
                              >
                                <Link className="w-3 h-3 mr-1" />
                                Resource Link
                              </a>
                            )}
                          </div>
                        </div>
                      </div>

                      <div className="flex items-center justify-between pt-4 border-t border-gray-100">
                        <div className="flex items-center gap-3">
                          {business.offerPrice && (
                            <span className="text-lg font-semibold text-green-600">
                              ₹{business.offerPrice}
                            </span>
                          )}
                          {business.mrp &&
                            business.offerPrice &&
                            business.mrp !== business.offerPrice && (
                              <span className="text-sm text-gray-500 line-through">
                                ₹{business.mrp}
                              </span>
                            )}
                        </div>
                        <button
                          onClick={() =>
                            openSharePopup(business.Sharelink, business.title)
                          }
                          className={`p-2 rounded-lg transition-all duration-200 ${
                            business.Sharelink
                              ? "hover:bg-gray-100 text-gray-500 hover:text-gray-700 cursor-pointer"
                              : "bg-gray-100 text-gray-400 cursor-not-allowed opacity-50"
                          }`}
                          title={
                            business.Sharelink
                              ? "Share this business"
                              : "Share link not available - contact support"
                          }
                          disabled={!business.Sharelink}
                        >
                          <Share2 className="w-5 h-5" />
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              </>
            )}
          </div>
        </div>
      </div>
      {/* Business Form Modal */}
      <BusinessForm
        isOpen={isFormOpen}
        onClose={closeForm}
        onCreated={handleCreated}
      />
      {/* Share Popup */}
      <SharePopup
        isOpen={sharePopup.isOpen}
        onClose={closeSharePopup}
        businessShareLink={sharePopup.businessShareLink}
        businessTitle={sharePopup.businessTitle}
      />
    </div>
  );
}
